### ISSUE TITLE
Is it possible to get the stream from the camera (simulating the app)? I want to pipe the stream to another application

### ISSUE THREAD

**Issue by ghost** [dunderhay/CCTV-v380-pro#4]

**Comment by dunderhay** [comment]
Yes it is possible to receive the video feed

**Comment by wmdebrito** [comment]
do you mind proving a piece of code where you can reproduce the video frorm the relay server? I tried with your code the you used to inject the video, but I was not able to get it working. I think my data packages are slightly different from yours

**Comment by dunderhay** [comment]
I do not have that code to share sorry. A friend of mine wrote something to decode the video stream from the relay server - which is how I know it is possible.
