### ISSUE TITLE
How to stream in VLC using data received from findcam.py

### ISSUE THREAD

**Issue by Arvinth-Krishna** [dunderhay/CCTV-v380-pro#5]
[*] Looking for IP Camera on the local network...
[+] Camera found: b'NVDEVRESULT^200^90:de:80:08:86:fc^192.168.1.1^255.255.255.0^192.168.1.1^5040^5050^5051^8800^7050^5040^59709732^0^1'

using this is there any way I can stream directly to VLC?

**Comment by dunderhay** [comment]
If you want to stream video from a camera on the local network using VLC, you can add it like this: 

<img width="561" alt="image" src="https://user-images.githubusercontent.com/27876907/233507440-2c428219-2562-48ec-8873-1ce926a92e1a.png">
